Add problems `chain` and `polygon`
MadNLP/COPSBenchmark.jl pull request #5
Opened 2024-02-27 00:16 UTC by tmigot

@frapac I kept the existing docstring, but we should probably unify with the other problems, what do you think?

2024-02-27 09:04 UTC, frapac requested changes
Thank you for your contribution @tmigot ! 
I only have a few suggestions, summarizing to:
- passing explicitly the arguments to the functions 
- using the newest NLP backend in JuMP (ie replacing `@NLobjective` by `@objective` and equivalently for `@NLconstraint`). This is required to support ExaModels.

The docstrings look good to me. Maybe add a line to specify that these two models are taken from `OptimizationProblems.jl`?

2024-02-27 09:04 UTC, frapac commented on src/chain.jl
> +function chain_model(args...; n::Int = default_nvar, kwargs...)
I would suggest to make the argument explicit here, as 
```julia
function chain_model(n::Int) 
```
what do you think?

2024-02-27 09:04 UTC, frapac commented on src/chain.jl
> +  @NLobjective(nlp, Min, x2[nh + 1])
We have to formulate the problem with `ScalarNonlinearFunction` in MOI to support ExaModels. As such, we have to formulate all nonlinear expressions with `@objective` and `@constraint`.

2024-02-27 09:04 UTC, frapac commented on src/chain.jl
> +  @NLconstraint(
Can we reformulate this expression with `@constraint` ?

2024-02-27 09:04 UTC, frapac commented on src/chain.jl
> +  @NLconstraint(
Can we reformulate this expression with `@constraint` ?

2024-02-27 09:04 UTC, frapac commented on src/polygon.jl
> +function polygon_model(args...; n::Int = default_nvar, kwargs...)
As in the previous function, I would suggest making all the arguments explicit. How about using? 
```julia
function polygon_model(n::Int)
```

2024-02-27 09:04 UTC, frapac commented on src/polygon.jl
> +      @NLconstraint(nlp, r[i]^2 + r[j]^2 - 2 * r[i] * r[j] * cos(θ[i] - θ[j]) - 1 <= 0)
Can we reformulate this expression with `@constraint` ?

2024-02-27 09:04 UTC, frapac commented on src/polygon.jl
> +  @NLobjective(nlp, Min, -0.5 * sum(r[i] * r[i + 1] * sin(θ[i + 1] - θ[i]) for i = 1:(N - 1)))
Can we reformulate this expression with `@objective` ?

2024-02-28 10:46 UTC, frapac approved these changes
Looks good to me, thank you!

2024-02-28 12:43 UTC, tmigot commented
@frapac I added the includes in the main file :). As mentioned in the report, polygon has several local minima so it is hard to test the objective value there.

2024-02-28 19:47 UTC, merged